name: CI Pipeline

on: [push]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test

  fmt:
    name: Rust fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D clippy::all -D clippy::pedantic -D warnings

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=x86_64-unknown-linux-musl

  build-all:
    runs-on: ${{ matrix.os }}
    if: github.ref == 'refs/heads/master'
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-latest, macos-latest, windows-latest, windows-latest]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            name: x86_64-linux-rustdsplit
            path: target/x86_64-unknown-linux-musl/release/rustdsplit
          - os: ubuntu-latest
            target: i686-unknown-linux-musl
            name: x86-linux-rustdsplit
            path: target/i686-unknown-linux-musl/release/rustdsplit
          - os: macos-latest
            target: x86_64-apple-darwin
            name: x86_64-macos-rustdsplit
            path: target/x86_64-apple-darwin/release/rustdsplit
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            name: x86_64-windows-rustdsplit.exe
            path: target\x86_64-pc-windows-msvc\release\rustdsplit.exe
          - os: windows-latest
            target: i686-pc-windows-msvc
            name: x86-windows-rustdsplit.exe
            path: target\i686-pc-windows-msvc\release\rustdsplit.exe
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.path }}

